#Region ;**** Directives created by AutoIt3Wrapper_GUI ****
#AutoIt3Wrapper_Icon=..\..\Artwork\Van Peter\turtlestitchlogo.ico
#EndRegion ;**** Directives created by AutoIt3Wrapper_GUI ****
#cs ----------------------------------------------------------------------------

	 AutoIt Version:
	 Author:         Hans de Jong

	 Script Function:


#ce ----------------------------------------------------------------------------

; -----------------------------------------
; Make sure to update the version number when having made changes
; -----------------------------------------

$Version="Version 0.1"

if @Compiled=False then $Version = stringreplace(@ScriptName,".au3","")

#Region (=== GUI generated by GuiBuilderPlus 1.3.0 ===)
Global $hGUI_TSUSBClear
Global $txtName, $mlblExplanation, $Label_2, $mlblName, $cmbLanguage, $mlblVersion, $btnNext, $mlblLanguage
Global $mlblDescription, $mtxtDescription, $mlblResult, $txtResult, $btnAbort, $btnOpenExplorer, $mtxtResult

;ConsoleWrite(IsStickEmpty("F:\*") & @crlf)

;Exit

; -----------------------------------------
; #includes
; -----------------------------------------
;~ #include <MsgBoxConstants.au3>
;~ #include <StringConstants.au3>
;~ #include <Misc.au3>
;~ #include <WinAPIvkeysConstants.au3>
;~ #include <WinAPIFiles.au3>
;~ #include <FileConstants.au3>
;~ #include <Array.au3>
;~ #include <File.au3>
#include <WinAPIShellEx.au3>
;~ #include <AutoItConstants.au3>
;~ #include <GuiConstantsEx.au3>
;~ #include <TreeViewConstants.au3>
;~ #include <AVIConstants.au3>
;~ #include <GUIConstantsEx.au3>
;~ #include <WindowsConstants.au3>
;~ #include <EditConstants.au3>
;~ #include <ProgressConstants.au3>
;~ #include <StaticConstants.au3>
#include <Date.au3>
;~ #include <Debug.au3>
;~ #include <WindowsStylesConstants.au3>
;#include "E:\Hans\Documents\AutoIT\CompInfo.au3"

;ConsoleWrite(_ComputerGetMotherboard() & @CRLF)
 ;Exit

;First find the path of the download folder on this machine
Local $s_Path_Downloads = _WinAPI_ShellGetKnownFolderPath($FOLDERID_Downloads)
Local $s_Path_Documents = _WinAPI_ShellGetKnownFolderPath($FOLDERID_Documents)
Local $s_Path_Desktop = _WinAPI_ShellGetKnownFolderPath($FOLDERID_Desktop)


;~ $USBstickPrefixTurtleSt = "TURTLEST"
;~ $USBstickPrefixUpdate = "UPDATETS"

;~ Local Const $ResultsTopFolder = $s_Path_Documents & "\turtlestitch\Results\" & NowDate()
;~ Local Const $NormalFolder = "Normal"
;~ Local Const $SpecialFolder = "Special"
;~ Local Const $TSOldPrefix = "TSOLD"

;~ $ExtraDataFileName="ExtraData.txt"




;$Today=NowDate()

;Local Const $ResultsNormalFolder = $ResultsTopFolder & "\" & $NormalFolder
;Local Const $ResultsSpecialFolder = $ResultsTopFolder & "\" & $SpecialFolder

;ConsoleWrite("$ResultsNormalFolder=" & $ResultsNormalFolder & @CRLF)
;ConsoleWrite("$ResultsSpecialFolder=" & $ResultsSpecialFolder & @CRLF)

FileWriteLine($s_Path_Downloads & "\TurtleSTimelog.txt" ,"TSStart=" & NowAsString() & @CRLF)


ShellExecute("https://turtlestitch.org/run")

Exit






Func NowAsString()
		local $Now= _NowCalc()
		;ConsoleWrite("Now=" & $Now & @CRLF)
		$Now=stringreplace($Now,"/","-")
		$Now=StringReplace($Now," ","--")
		$Now=StringReplace($Now, ":", "-")
		;ConsoleWrite("Now=" & $Now & @CRLF)
		Return $Now
EndFunc





Func SplitTimeDateString($TimeDateString)
	; split YYYMMDDHHMMSS string into YYYY-MM-DD HH:MM:SS
	Local $SplittedString = StringLeft($TimeDateString, 4) & "-" & StringMid($TimeDateString, 5, 2) & "-" & StringMid($TimeDateString, 7, 2)
	$SplittedString = $SplittedString & " " & StringMid($TimeDateString, 9, 2) & ":" & StringMid($TimeDateString, 11, 2) & ":" & StringRight($TimeDateString, 2)
	ConsoleWrite($SplittedString & @CRLF)
	Return $SplittedString
EndFunc   ;==>SplitTimeDateString
