#cs ----------------------------------------------------------------------------

	 AutoIt Version:
	 Author:         Hans de Jong

	 Script Function:


#ce ----------------------------------------------------------------------------

; -----------------------------------------
; Make sure to update the version number when having made changes
; -----------------------------------------

$Version="Version 0.1"

if @Compiled=False then $Version = stringreplace(@ScriptName,".au3","")

#Region (=== GUI generated by GuiBuilderPlus 1.3.0 ===)
Global $hGUI_TSUSBClear
Global $txtName, $mlblExplanation, $Label_2, $mlblName, $cmbLanguage, $mlblVersion, $btnNext, $mlblLanguage
Global $mlblDescription, $mtxtDescription, $mlblResult, $txtResult, $btnAbort, $btnOpenExplorer

;ConsoleWrite(IsStickEmpty("F:\*") & @crlf)

;Exit

; -----------------------------------------
; #includes
; -----------------------------------------
#include <MsgBoxConstants.au3>
#include <StringConstants.au3>
#include <Misc.au3>
#include <WinAPIvkeysConstants.au3>
#include <WinAPIFiles.au3>
#include <FileConstants.au3>
#include <Array.au3>
#include <File.au3>
#include <WinAPIShellEx.au3>
#include <AutoItConstants.au3>
#include <GuiConstantsEx.au3>
#include <TreeViewConstants.au3>
#include <AVIConstants.au3>
#include <GUIConstantsEx.au3>
#include <WindowsConstants.au3>
#include <EditConstants.au3>
#include <ProgressConstants.au3>
#include <StaticConstants.au3>
#include <Date.au3>
#include <Debug.au3>
#include <WindowsStylesConstants.au3>
;#include "E:\Hans\Documents\AutoIT\CompInfo.au3"

;ConsoleWrite(_ComputerGetMotherboard() & @CRLF)
 ;Exit

;First find the path of the download folder on this machine
Local $s_Path_Downloads = _WinAPI_ShellGetKnownFolderPath($FOLDERID_Downloads)
Local $s_Path_Documents = _WinAPI_ShellGetKnownFolderPath($FOLDERID_Documents)
Local $s_Path_Desktop = _WinAPI_ShellGetKnownFolderPath($FOLDERID_Desktop)


$USBstickPrefixTurtleSt = "TURTLEST"
$USBstickPrefixUpdate = "UPDATETS"

Local Const $ResultsTopFolder = $s_Path_Documents & "\turtlestitch\Results\" & NowDate()
Local Const $NormalFolder = "Normal"
Local Const $SpecialFolder = "Special"
Local Const $TSOldPrefix = "TSOLD"

$ExtraDataFileName="ExtraData.txt"

Global Const $BackgroundColorNormal = 0x008000
Global Const $ForegroundColorNormal = 0xFFFFFF

Global Const $BackgroundColorError = 0xFF0000
Global Const $ForegroundColorError = 0xFFFFFF

Global Const $BackGroundColorEmpty = 0x80FF80
Global Const $ForegroundColorEmpty = 0x000000

Global Const $BackgroundColorWarning = 0xFFFF80
Global Const $ForegroundColorWarning = 0x000000

global $USBStickBeingProcessed = False
Global $DriveForShellExecute


$Today=NowDate()

Local Const $ResultsNormalFolder = $ResultsTopFolder & "\" & $NormalFolder
Local Const $ResultsSpecialFolder = $ResultsTopFolder & "\" & $SpecialFolder

ConsoleWrite("$ResultsNormalFolder=" & $ResultsNormalFolder & @CRLF)
ConsoleWrite("$ResultsSpecialFolder=" & $ResultsSpecialFolder & @CRLF)

If Not FileExists($ResultsNormalFolder) Then $reulst=DirCreate ($ResultsNormalFolder)
If Not FileExists($ResultsSpecialFolder) Then $reulst=DirCreate ($ResultsSpecialFolder)




;-----------------------------
;---- Update the language to take into account the system language
;-----------------------------

Global $SupportedLanguages
; Language defines
$LangEnglish = "09"
$LangDutch = "13"
$LangGerman = "07"
$LangDanish = "06"
$LangItalian = "10"
$LangSweden = "1D"
$LangTurkish = "1F"
$LangSpanish = "0A"
$LangFrench = "OC"


;$SupportedLanguages = $LangEnglish & "|" & $LangDutch & "|" & $LangGerman & "|" & $LangDanish & "|" & $LangTurkish

Global Const $LanguageActive = 0
Global Const $LanguageName = 1
Global Const $LanguageNumber = 2
Global Const $LanguageDetailWindowX = 3
Global Const $LanguageDetailWindowY = 4

Global $LanguageArray[9][5]=[ _
	[  True, "English", $LangEnglish, 0, 0 ], _
	[  True, "Nederlands", $LangDutch, 0, 0 ], _
	[  True, "Deutsch", $LangGerman, 0, 0 ], _
	[  True, "Dansk", $LangDanish, 0, 0 ] , _
	[  False, "Italiano", $LangItalian, 0, 0 ] , _
	[  False, "Svenska", $LangSweden, 0 ], _
	[  True, "Türkçe", $LangTurkish, 0 ], _
	[  False, "Español", $LangSpanish, 0, 0 ], _
	[  False, "Français", $LangFrench, 0 ] _
	]

; create the string with all supported languages
Local $i
For $i = 0 to UBound($LanguageArray, 1) - 1

	if $LanguageArray[$i][$LanguageActive] = True then
		if $i <> 0 then $SupportedLanguages=$SupportedLanguages & "|"
		$SupportedLanguages=$SupportedLanguages & $LanguageArray[$i][ $LanguageName]
	EndIf
Next

ConsoleWrite ("SupportedLanguages=" & $SupportedLanguages & @CRLF)



;$LanguageArray[$Language,$OSLanguageIndex] = $OSLangDutch

; First set the default language to English
$Language=$LangEnglish

$ConfigLanguage = "OS"

If $ConfigLanguage = "OS" Then
	ConsoleWrite(@OSLang & @CRLF)
	$OSLanguageNumber = StringMid(@OSLang, 3, 2)
	ConsoleWrite("OSLang=" & $OSLanguageNumber & @CRLF)

	;look whether the language is supported. If so, choose that language, otherwise the default English stays

	for $i=0 to UBound($LanguageArray, 1) - 1
		if $OSLanguageNumber = $LanguageArray [$i][$LanguageNumber] then
			; the OS language is supported, therefore set the language to the OS language
			$Language=$OSLanguageNumber
			ExitLoop
		EndIf
	Next
else
	$Language=LanguageName2Language($ConfigLanguage)
EndIf

ConsoleWrite("Language="& $Language & @CRLF)

func LanguageName2Language ($LangName)
	; First set the default language to English
	Local $Lang=$LangEnglish
	for $i=0 to UBound($LanguageArray, 1) - 1
		if $LangName = $LanguageArray [$i][ $LanguageName] then
			$Lang=$LanguageArray[$i][ $LanguageNumber]
			ExitLoop
		EndIf
	Next
	Return $Lang
EndFunc

func Language2Index ($Lang)
	; First set the default language to English
	for $i=0 to UBound($LanguageArray, 1) - 1
		if $Lang = $LanguageArray [$i][ $LanguageNumber] then
			Return $i
		EndIf
	Next

EndFunc


;----------------------------------------------------------------
;--- Set strings in local language
;----------------------------------------------------------------





; Now set the stings in the local language for the first time. This is also done each time after a change in language is made
SetMessagesInLanguage()

Func SetMessagesInLanguage()

	; Note that all messages that are conditionally displayed in the Details panel have a Flag variable as well. This is because we must show the correct translated message
	; The error message to be displayed is remembered based on the flag. This holds for error messages as well as the message for the location of the .XML file

	; The settings for English will always be set, so that they are the default in case a language is not supported or not all strings have been translated for that language



	Switch $Language
		Case $LangDutch
		Case $LangGerman
		Case $LangDanish
		case $LangTurkish
	EndSwitch


EndFunc   ;==>SetMessagesInLanguage










;ConsoleWrite($s_Path_Downloads & @CRLF)
;ConsoleWrite($s_Path_Documents & @CRLF)
;ConsoleWrite($s_Path_Desktop & @CRLF)



$DBT_DEVICEARRIVAL = "0x00008000"
;$WM_DEVICECHANGE = 0x0219

;$hGUI1 = GUICreate("")
_guiCreate()
GUISetState(@SW_SHOWNORMAL)
GUICtrlSetState($btnNext,$gui_disable)
GUICtrlSetState($btnOpenExplorer,$gui_disable)

GUIRegisterMsg($WM_DEVICECHANGE, "USBstickDetection")


While 1
	Switch GUIGetMsg()
		Case $GUI_EVENT_NONE
			;ConsoleWrite("voor continueloop"&@CRLF)
			Sleep(100)         ; this is essential to make sure that the window responds
			ContinueLoop
		Case $GUI_EVENT_CLOSE    ;this is when closing the window
			Msgbox(64,"stopping","Stopping because of closing the window")
			exit
			$WhichButtonPressed = 0
			ExitLoop
		Case $btnNext
			_WinAPI_EjectMedia($DriveForShellExecute)
			GUICtrlSetState($btnNext,$gui_disable)
			GUICtrlSetState($btnOpenExplorer,$gui_disable)

			ContinueLoop

		Case $btnAbort
			ConsoleWrite("exit button pressed" & @CRLF)
			$WhichButtonPressed = 2
			;DisplayPanel(1, $h_MessageGUI, $hdrReallyStop, $msgSure2StopTheScript, $mbtnOK, $mbtnCancel, "") = 1 Then Exit

			;if (msgbox($MB_OKCANCEL+$MB_ICONQUESTION,$hdrAbort,$msgSure2StopTheScript)) = $IDOK then
			Msgbox(64,"stopping","Stopping because of pressing Abort")
			Exit
			;endif
			ExitLoop

		Case $cmbLanguage
			$sComboRead = GUICtrlRead($cmbLanguage)
			; test that indeed a new language has been set

				Local $CurrentSize = WinGetClientSize($hGUI_TSUSBClear)
				ConsoleWrite("Language WindowSizeX=" & $CurrentSize[0] & " WindowSizeY=" & $CurrentSize[1] & @CRLF)

				;save the window sizes for this language
				Local $index = Language2Index($Language)
				$LanguageArray[$index][$LanguageDetailWindowX]=$CurrentSize[0]
				$LanguageArray[$index][$LanguageDetailWindowY]=$CurrentSize[1]



			If $sComboRead <> "" And $sComboRead <> $LanguageArray[Language2Index($Language)][$LanguageName] Then
				; a new language was chosen
				$Language = LanguageName2Language($sComboRead)  ;set the new language
				$LanguageChanged = True  ;make sure we make a next round with the strings in the new language

				SetMessagesInLanguage()    ;update all the message strings to the correct language
				;ExitLoop
			EndIf

		Case $btnOpenExplorer

			ShellExecute($DriveForShellExecute & "\")
			;GUICtrlSetState($btnNext,$gui_disable)
			;UICtrlSetState($btnOpenExplorer,$gui_disable)

			;_WinAPI_EjectMedia($DriveForShellExecute)

			ContinueLoop



	EndSwitch

WEnd



; Waint forever. The processing starts when a USB stick is inserted
While (1)
	Sleep(1000000)
WEnd


;------------------------------------------------------
; Title...........:	_guiCreate
; Description.....:	Create the main GUI
;------------------------------------------------------
Func _guiCreate()

	$mlblExplanation="This is to move all turtlestitch (.DST, .XML and ExtraData.txt) files from the USB stick to the computer. Also all the TurtleStitch backup folders will be moved. If you want to make notes to later process the material, then "
	$mlblExplanation=$mlblExplanation & "fill in the Name field and optionally a more elaborate text in the Description box. But do this before inserting the USB stick that it concerns. "
	$mlblExplanation=$mlblExplanation & "Generally the USB stick will automatically be ejected. If it is, then it is indicated."

	$hGUI_TSUSBClear = GUICreate("TSUSB-Clear", 832, 600, 210, 30, BitOR($WS_SIZEBOX, $WS_MINIMIZEBOX))

	$txtName = GUICtrlCreateInput("", 160, 100, 206, 21)
	$mlblExplanation = GUICtrlCreateLabel($mlblExplanation, 20, 10, 796, 71)
	$mlblName = GUICtrlCreateLabel("Name", 20, 100, 116, 21)
	$cmbLanguage = GUICtrlCreateCombo("Combo 1", 675, 100, 141, 20)
	$mlblVersion = GUICtrlCreateLabel("Version", 680, 540, 106, 21)
	$btnNext = GUICtrlCreateButton("Next (eject)", 20, 525, 176, 36, $GUI_DISABLE)
	$mlblLanguage = GUICtrlCreateLabel("Language", 565, 100, 91, 21)
	$mlblDescription = GUICtrlCreateLabel("Description", 20, 140, 111, 21)
	$mtxtDescription = GUICtrlCreateEdit("", 20, 170, 811, 276, BitOR($ES_AUTOVSCROLL, $ES_MULTILINE, $ES_WANTRETURN))
	$mlblResult = GUICtrlCreateLabel("Result", 20, 455, 131, 26)
	$txtResult = GUICtrlCreateEdit("", 160, 450, 661, 50, BitOR($ES_MULTILINE, $ES_AUTOVSCROLL, $ES_READONLY) )
	$btnAbort = GUICtrlCreateButton("Abort", 390, 525, 176, 36)
	$btnOpenExplorer = GUICtrlCreateButton("Open USB Stick", 205, 525, 176, 36, $GUI_DISABLE)


EndFunc   ;==>_guiCreate
#EndRegion (=== GUI generated by GuiBuilderPlus 1.3.0 ===)



Exit



Func USBstickDetection($hWndGUI, $MsgID, $WParam, $LParam)
	ConsoleWrite("USBbeingprocessed="& $USBStickBeingProcessed & @crlf)

	if $USBStickBeingProcessed = true Then
		Return
	Else
		$USBStickBeingProcessed = true
	EndIf
	; if shift (left or right) is pressed while inserting the USB stick then a menu will pop up with the option to stop the script
	; Also the language can be changed as on every panel
	If IsShiftPressed() Then
		; Display the two buttons. The second (2) is the exit button
		; ---> DisplayPanel(1, $hGUI1, $hdrStopScript, "", $btnContinue, $mbtnEndScript, "", 2)
		Msgbox(64,"stopping","Stopping because of SHIFT pressed")
		exit
	EndIf

	; msgbox(4096,"bla",$MsgID,2)
		sleep (1000)
	Local $aArray = DriveGetDrive($DT_REMOVABLE)
	Local $i
	If @error Then
		; An error occurred when retrieving the drives.
		ConsoleWrite ("It appears an error occurred after DriveGetDrive." & @CRLF)
	Else

		;Go through all driveletters with removable drives and see whether it is the one for TurtleStitch
		ConsoleWrite("Number of drives = " & $aArray[0] & @CRLF)
		$USBvolume=""
		For $i = 1 To $aArray[0]
			sleep (1000)
			; Get the driveletters of the removable drives
			Local $DriveLetter = $aArray[$i]
			ConsoleWrite("$DriveLetter=" & $DriveLetter & @CRLF)
			; Get the volumelabel given the driveletter
			$USBvolume = DriveGetLabel($DriveLetter)
			if $USBvolume="" Then
				ConsoleWrite("after blank USB volume, @error=" & @error & @crlf)

				$bArray = DriveGetDrive($DT_REMOVABLE)
				ConsoleWrite("After blank USB volume, number of drives =" & $bArray[0] & @CRLF)

			else

				if @error = 2 Then  ; 2 is wrong, should be 1, to be looked at later
					ConsoleWrite("416 $USBvolume=" & $USBvolume & @CRLF)
					_WinAPI_EjectMedia($DriveLetter)

					GUICtrlSetData($txtResult,"Volume label could not be obtained. Remove the USB stick. It is already ejected")
					GUICtrlSetBkColor($txtResult,$BackgroundColorError)
					GUICtrlSetColor($txtResult,$ForegroundColorError)
				else
					ConsoleWrite("396 $USBvolume=" & $USBvolume & @CRLF)
					Local $result = 2
					;MsgBox(0,"label", $DriveLetter)

					If StringInStr($USBvolume, $USBstickPrefixTurtleSt, 1) = 1 Then
						consolewrite ("aDriveletter="&$DriveLetter& "\*" & "b" & @CRLF)
						$Path4Sizearray=$DriveLetter&"\*"
						$result=IsStickEmpty($Path4Sizearray)

						if $result=true then

							_WinAPI_EjectMedia($DriveLetter)

							GUICtrlSetData($txtResult,"The stick is already empty. Volumelabel = " & $USBvolume & ". Remove the USB stick. It is already ejected")
							GUICtrlSetBkColor($txtResult,$BackGroundColorEmpty)
							GUICtrlSetColor($txtResult,$ForegroundColorEmpty)
						else

							ConsoleWrite("voor MoveTSfiles" & @crlf)
							$result = MoveTSfilesFromStick( $DriveLetter, $USBvolume)

							consolewrite("after moveTS. Result="& $result & @CRLF)

							if $result=2 Then
								$Path4Sizearray=$DriveLetter&"\*"
								$result=IsStickEmpty($Path4Sizearray)

								if $result=false then
								;if $sizearray[1] + $sizearray[2] <> 0 Then
									FileClose ($result)
									GUICtrlSetData($txtResult,"TurtleStitch content (if any) of USB stick " & $USBvolume & " has been copied, but the stick is not empty. Click Next or click Open USB Stick, inspect and then click Next to eject.")
									GUICtrlSetBkColor($txtResult,$BackgroundColorWarning)
									GUICtrlSetColor($txtResult,$ForegroundColorWarning)
									;$result=FileFindFirstFile($Path4Sizearray)
									;if $result=-1 then
									GUICtrlSetData($mtxtDescription,"")
									GUICtrlSetData($txtName,"")

									$DriveForShellExecute=$DriveLetter
									GUICtrlSetState($btnNext,$GUI_ENABLE)
									GUICtrlSetState($btnOpenExplorer,$GUI_ENABLE)

								else
									_WinAPI_EjectMedia($DriveLetter)

									GUICtrlSetData($txtResult,"Content of USB stick " & $USBvolume & " has been copied. Remove the USB stick. It is already ejected")
									GUICtrlSetBkColor($txtResult,$BackgroundColorNormal)
									GUICtrlSetColor($txtResult,$ForegroundColorNormal)
									GUICtrlSetData($mtxtDescription,"")
									GUICtrlSetData($txtName,"")

								EndIf
							else
								;_WinAPI_EjectMedia($DriveLetter)
								GUICtrlSetData($txtResult,"Something went wrong. Volumelabel = " & $USBvolume & ". Remove the USB stick. It is already ejected")
								GUICtrlSetBkColor($txtResult,$BackgroundColorError)
								GUICtrlSetColor($txtResult,$ForegroundColorError)
							endif


						EndIf
					Else
						if $USBvolume <> "" then
							_WinAPI_EjectMedia($DriveLetter)
							GUICtrlSetData($txtResult,"This is not a TurtleStitch stick. Volumelabel = " & $USBvolume & ". Remove the USB stick. It is already ejected")
							GUICtrlSetBkColor($txtResult,$BackgroundColorWarning)
							GUICtrlSetColor($txtResult,$ForegroundColorWarning)
						endif

					EndIf
				EndIf
			EndIf
			;msgbox(0,"USB drive",$USBvolume,2)
		Next



		; DBT_DEVICEREMOVECOMPLETE
	EndIf
	ConsoleWrite("Setting to False"&@CRLF)
	$USBStickBeingProcessed = False
EndFunc   ;==>USBstickDetection


func IsStickEmpty($Path)

	local $h_search=FileFindFirstFile($Path)
	if $h_search= -1 Then
		return True
	Else
		while 1
			local $filename = FileFindNextFile($h_search)
			if @error then ExitLoop
			consolewrite ($filename & @crlf)
			if $filename <> "System Volume Information" then
				fileclose($h_search)
				return false
			endif
		WEnd
		fileclose($h_search)
		return True
	EndIf
EndFunc


Func NowAsString()
		local $Now= _NowCalc()
		;ConsoleWrite("Now=" & $Now & @CRLF)
		$Now=stringreplace($Now,"/","-")
		$Now=StringReplace($Now," ","--")
		$Now=StringReplace($Now, ":", "-")
		;ConsoleWrite("Now=" & $Now & @CRLF)
		Return $Now
EndFunc

Func NowDate()
	Return StringLeft(NowAsString(), 10)
EndFunc



Func MoveTSfilesFromStick($USBDriveLetter, $USBvolume)



	Local $Dir2Test = $USBDriveLetter & "\"
	ConsoleWrite("aa" & $USBDriveLetter & "bb")
	If FileExists($Dir2Test) = 0 Then

		;$result = DisplayPanel(1, $hGUI1, $hdrFailure, $msgNoUSBStick, $mbtnOK, "", "")
		;MsgBox($MB_ICONERROR, "Geen USB Stick", $msgNoUSBStick)
		ConsoleWrite("There is no USB stick" & @CRLF)

		Return 1
	EndIf

	;ClearUSBStick($USBDriveLetter)



	If FileExists($USBDriveLetter & "\*.DST") or FileExists($USBDriveLetter & "\" & $ExtraDataFileName) or FileExists($USBDriveLetter & "\" & $TSOldPrefix & "*") Then
		Local $Now=NowAsString()
		;_DebugSetup

		local $NameExt = GUICtrlRead($txtName)
		if $NameExt="" then
			$TargetDir = $ResultsNormalFolder & "\" & $USBvolume & "-" & $Now
		Else
			$DescriptionText=GUICtrlRead($mtxtDescription)
			$TargetDir = $ResultsSpecialFolder & "\" & $USBvolume & "-" & $Now & "-" & $NameExt
			$h_file=Fileopen($TargetDir & "\DataWhenEmptied.txt",bitor ( $FO_OVERWRITE ,$FO_CREATEPATH ))
			ConsoleWrite("h_file=" & $h_file & @CRLF)
			ConsoleWrite("x" & $DescriptionText & "x" & @CRLF)
			$result=Filewrite($h_file,$DescriptionText)
			ConsoleWrite("$result=" & $result & @crlf)
			FileClose($h_file)

		EndIf
		$result=DirCreate($TargetDir)

		$result=MoveMultipleFilesOrDirs($USBDriveLetter&"\","*.DST", $TargetDir)
		ConsoleWrite("Filemove DST result=" & $result & @CRLF)
		$result=MoveMultipleFilesOrDirs($USBDriveLetter&"\","*.XML", $TargetDir)
		ConsoleWrite("Filemove XML result=" & $result & @CRLF)
		$result=MoveMultipleFilesOrDirs($USBDriveLetter & "\", $ExtraDataFileName, $TargetDir)
		ConsoleWrite("Filemove Extrafile result=" & $result & @CRLF)
		$result=MoveMultipleFilesOrDirs($USBDriveLetter & "\" , $TSOldPrefix & "*", $TargetDir)
		ConsoleWrite("Dirmove TSOLD result=" & $result & @CRLF)

	EndIf
	Return 2

EndFunc   ;==>MoveTSfilesFromStick

func MoveMultipleFilesOrDirs ($Path, $SearchString, $TargetDir)
	; Assign a Local variable the search handle of all files in the current directory.
	Local $fullpath=$Path & $SearchString
    Local $hSearch = FileFindFirstFile($fullpath)
	;ConsoleWrite("fullpath="& $fullpath & @CRLF)
    ; Check if the search was successful, if not display a message and return False.
    If $hSearch = -1 Then
        return True
    EndIf

    ; Assign a Local variable the empty string which will contain the files names found.
    Local $sFileName = "", $iResult = 0

    While 1
        $sFileName = FileFindNextFile($hSearch)
        ; If there is no more file matching the search.
        If @error Then ExitLoop

		;consolewrite("$sFileName="&$sFileName&@CRLF)
        ; Display the file name.
		;consolewrite("fileattrib=" & FileGetAttrib($Path & $sFileName) & @CRLF)
		$dirtest=StringInStr(FileGetAttrib($Path & $sFileName),"D")

		;ConsoleWrite("$dirtest=" & $dirtest & @crlf		)

		if $dirtest<>0 Then
			$fullpath=$Path & $sFileName
			;consolewrite ("$fullpath="&$fullpath&"  target=" & $TargetDir)
			$iResult = DirMove ($Path & $sFileName,$TargetDir & "\" & $sFileName)
			consolewrite("$iResult Dirmove=" & $iResult & @CRLF)
		Else
			$iResult = FileMove ($Path & $sFileName,$TargetDir, $FC_Overwrite)
			ConsoleWrite("$iresult filemove=" & $iresult & @CRLF)
		EndIf

        ;If $iResult <> $IDOK Then ExitLoop
    WEnd

    ; Close the search handle.
    FileClose($hSearch)
	return $iResult

EndFunc



; This function checks whether one of the Shift keys is pressed and returns TRUE if so. False otherwise
Func IsShiftPressed()
	Local $hDLL = DllOpen("user32.dll")
	If _IsPressed("10", $hDLL) Then
		; ConsoleWrite("_IsPressed - Shift Key was pressed. @extended = " & @extended & @CRLF)
		Return True
	Else
		Return False
	EndIf
	DllClose($hDLL)
EndFunc   ;==>IsShiftPressed


Func StripComment($Text)
	Return StringStripWS(StringRegExpReplace($Text, ";.*", ""), $STR_STRIPALL)
EndFunc   ;==>StripComment

Func DisplayPanel($Type, $Window2Disable, ByRef $HeaderText, ByRef $Message, ByRef $Button1, ByRef $Button2, ByRef $Button3, $ExitButtonNr = 0, $TimeOut = 0)
	; The intent of this function is to display a message for the user and also to allow select another language for the interface.
	; It can be called with an optional message text to be displayed and up to 3 buttons. One of the buttons can be defined as an exit
	; button. When that one is pressed, the whole script will exit.
	; $Type					= 1: display the $Message in a simple window
	;						= 2: Display the details panel
	; $Window2Disable 		= when called from another GUI, that GUI must be disabled while this new GUI is displayed
	;						  Fill in the handle of the other GUI. Or an empty string if no window is to be disabled
	; $HeaderText			= Text to display at the top of the Window
	; $MessageOrFlags		= Type=1 : Message that will be displayed. Or empty string if nothing is to be displayed
	;						= Type=2 : Combined message flags so that multiple messages can be displayed. This is done this way
	;							rather than concatenating the messages in the calling function because this allows for translations to be done when the panel is displayed
	; $Button1				= Text on the leftmost button. Or empty string if the button must not be displayed.
	; $Button2				= Text on the middle button. Or empty string if the button must not be displayed.
	; $Button3				= Text on the rightmost button. Or empty string if the button must not be displayed.
	; $ExitButtonNr			= Optional. Which of the buttons (1, 2 or 3) will trigger the script to terminate (after a confirmation)
	;						  Or 0 if none of them will have that behaviour.
	;
	; Return values
	; 						1, 2 or 3 when button1, button2 or button 3 are pressed respectively
	; 						When the button is pressed specified by $ExitButton then nothing is returned: the script is just terminated
	;
	; Side effects: the user can choose another language and that new value will be set in the $Language variable
	;
	; Note that when the language changes, the scripts sets the new language strings and loops to display the panel in the newly selected language.
	; Note that it is essential for most of the parameters to be ByRef, beacuse when the language changes, reference must be made to those updated values.

	If $Window2Disable <> "" Then GUISetState(@SW_DISABLE, $Window2Disable)

	Local $vchkIgnoreErrors, $txtPassword

	; make sure that at the while loop is executed at least once
	Local $LanguageChanged = True

	$WhichButtonPressed = 0
	Local $BoxHeight = 22
	Local $LabelYOffset = 4

	While $LanguageChanged = True

		; Set the value to False, since that is the outcome in most cases. It will be set to True when a language has indeed been changed.
		$LanguageChanged = False

		if $Type=1 then








		EndIf


		; sleep(500)
		; Make the window visible
		;GUISetState(@SW_SHOWNORMAL, $h_MessageGUI)
		ConsoleWrite("na GUISetState" & @CRLF)
		ConsoleWrite("Timeout=" & $TimeOut)
		If $Timeout<> 0 then AdlibRegister("CloseGUI") ;, $TimeOut)

		;sleep(500)


		GUIDelete($hGUI_TSUSBClear)


	WEnd

	consolewrite ("before reenabling the disabled window" & @CRLF)
	If $Window2Disable <> "" Then GUISetState(@SW_ENABLE, $Window2Disable)

	#EndRegion GUI MESSAGE LOOP

	ConsoleWrite("hier" & @CRLF)
	Return $WhichButtonPressed

EndFunc   ;==>DisplayPanel

Func CloseGUI()
	ConsoleWrite("CloseGui is called " & @crlf)
	;WinClose($GUIhandle2Close)
	AdlibUnRegister("CloseGUI")
endFunc


Func SplitTimeDateString($TimeDateString)
	; split YYYMMDDHHMMSS string into YYYY-MM-DD HH:MM:SS
	Local $SplittedString = StringLeft($TimeDateString, 4) & "-" & StringMid($TimeDateString, 5, 2) & "-" & StringMid($TimeDateString, 7, 2)
	$SplittedString = $SplittedString & " " & StringMid($TimeDateString, 9, 2) & ":" & StringMid($TimeDateString, 11, 2) & ":" & StringRight($TimeDateString, 2)
	ConsoleWrite($SplittedString & @CRLF)
	Return $SplittedString
EndFunc   ;==>SplitTimeDateString
